name: Build PR

on:
  pull_request:
    types: [synchronize]
jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install
        run: npm ci
      - name: Linting and Formatting
        run: npm run lint && npm run check-format
      - name: Unit tests
        run: npm run test
